name: Create OSSign PR

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set git user info
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo $GH_TOKEN | gh auth login --with-token
          gh auth status

      - name: Create PR to OSSign repo
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          gh pr create \
            --repo OSSign/Beaver-Notes--Beaver-Notes \
            --head Beaver-Notes:main \
            --base main \
            --title "Code signing request for new release" \
            --body "Please sign the new release from Beaver-Notes main branch."
